apiVersion: v1
kind: Secret
metadata:
  name: loki-secrets
  namespace: loki
type: Opaque
stringData:
  gcp_service_account.json: |
    {
      "type": " ",
      "project_id": " ",
      "private_key_id": " ",
      "private_key": "",
      "client_email": " ",
      "client_id": "",
      "auth_uri": "",
      "token_uri": "",
      "auth_provider_x509_cert_url": "",
      "client_x509_cert_url": ""
    }